  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: spring-app
    namespace: student-manij-izzatov
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: spring-app
    template:
      metadata:
        labels:
          app: spring-app
      spec:
        containers:
          - name: app
            image: ghcr.io/screem2020/koroche-practice-ci-cd:sha-123b33d        # напр. ghcr.io/you/app:latest
            ports:
              - containerPort: 8080
            envFrom:
              - configMapRef:
                  name: spring-app

