apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: student-manij-izzatov
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP